# Docker Compose for development
version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    volumes:
      - ./dist:/app/dist:ro
    restart: unless-stopped

  # Database service (if using PostgreSQL)
  # postgres:
  #   image: postgres:15-alpine
  #   environment:
  #     POSTGRES_DB: restaurant_db
  #     POSTGRES_USER: restaurant_user
  #     POSTGRES_PASSWORD: restaurant_password
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   ports:
  #     - "5432:5432"

# volumes:
#   postgres_data:
